# vim: set ts=2 et:

# run xvfb with 32-bit color
# xvfb-run -s '-screen 0 1600x1200x24+32' command_goes_here

matrix:
  include:

    # Python 3 + QT4
    - os: linux
      dist: trusty
      sudo: required
      language: generic
      python: "3.5"
      env:
        - QT=4
      addons:
        apt:
          packages:
            - cmake
            - python3-pyqt4
            - pyqt4-dev-tools
            - xvfb
      before_install:
        - sudo apt-get update
        - sudo apt-get install -y python3-pip
        - sudo pip3 install lxml
        - sudo pip3 install labelImg

    # Python 3 + QT5
    - os: linux
      dist: trusty
      sudo: required
      language: generic
      python: "3.5"
      env:
        - QT=5
      addons:
        apt:
          packages:
            - cmake
            - pyqt5-dev-tools
            - xvfb
      before_install:
        - sudo apt-get update
        - sudo apt-get install -y python3-pip
        - sudo pip3 install lxml
        - sudo pip3 install labelImg

script:
  - xvfb-run python3 -m unittest discover tests
