# vim: set ts=2 et:

# run xvfb with 32-bit color
# xvfb-run -s '-screen 0 1600x1200x24+32' command_goes_here

matrix:
  include:

    # Python 3 + QT4
    - os: linux
      dist: xenial
      sudo: required
      language: generic
      python: "3.5"
      env:
        - QT=4
      addons:
        apt:
          packages:
            - cmake
      before_install:
        - sudo apt-get update
        - sudo apt-get install -y python3-pip python3-pyqt4 pyqt4-dev-tools xvfb
        - sudo pip3 install lxml
        - make qt4py3
        - xvfb-run make testpy3

    # Python 3 + QT5
    - os: linux
      dist: xenial
      sudo: required
      language: generic
      python: "3.5"
      env:
        - QT=5
      addons:
        apt:
          packages:
            - cmake
      before_install:
        - sudo apt-get update
        - sudo apt-get install -y python3-pip pyqt5-dev-tools xvfb
        - sudo pip3 install lxml
        - make qt5py3
        - xvfb-run make testpy3

script:
  - exit 0
